=== franc90/DispatchRider/xml/schemes/clustable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ClusTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="structure" type="structureType"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="content" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="globalTableContent" type="contentType"
								minOccurs="0" maxOccurs="1" />
							<xs:element name="holonTableContent" type="contentType"
								minOccurs="0" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="observations" minOccurs="1" maxOccurs="1"
					type="globalHolonObservationsType" />
			</xs:sequence>
			<xs:attribute name="learning" type="xs:boolean" default="false" />
			<xs:attribute name="useTrees" type="xs:boolean" default="false" />
			<xs:attribute name="minClustCount" type="xs:string"
				default="2" />
			<xs:attribute name="maxClustCount" type="xs:string"
				default="sqrt(N)" />
			<xs:attribute name="usepam" type="xs:boolean" default="true" />
			<xs:attribute name="overwriteConf" type="xs:boolean"
				default="true" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="structureType">
		<xs:sequence>
			<xs:element name="globalMeasures" type="measuresType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="globalStates" type="statesType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="globalActions" type="actionsType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="holonMeasures" type="measuresType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="holonStates" type="statesType"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="holonActions" type="holonActionsType"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="measuresType">
		<xs:sequence>
			<xs:element name="measure" minOccurs="1" maxOccurs="unbounded"
				type="measureType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="measureType">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="statesType">
		<xs:sequence>
			<xs:element name="state" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="measure" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required" />
								<xs:attribute name="value" type="xs:string" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="k" type="xs:double" use="required" />
	</xs:complexType>

	<xs:complexType name="actionsType">
		<xs:sequence>
			<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="sendingType" type="xs:string"
						default="null" />
					<xs:attribute name="choosingByCost" type="xs:string"
						default="null" />
					<xs:attribute name="simmulatedTrading" type="xs:int"
						default="-1" />
					<xs:attribute name="STDepth" type="xs:int" default="-1" />
					<xs:attribute name="chooseWorstCommission" type="xs:string"
						default="null" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="function" type="xs:string" use="required" />
		<xs:attribute name="factor" type="xs:double" use="required" />
		<xs:attribute name="deterministic" type="xs:boolean"
			default="true" />
	</xs:complexType>


	<xs:complexType name="holonActionsType">
		<xs:sequence>
			<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="algorithm" type="xs:string"
						default="null" />
					<xs:attribute name="newCommissionCostByDist" type="xs:string"
						default="null" />
					<xs:attribute name="simmulatedTrading" type="xs:string"
						default="null" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="function" type="xs:string" use="required" />
		<xs:attribute name="factor" type="xs:double" use="required" />
		<xs:attribute name="deterministic" type="xs:boolean"
			default="true" />
	</xs:complexType>

	<xs:complexType name="contentType">
		<xs:sequence>
			<xs:element name="state" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required" />
								<xs:attribute name="useCount" type="xs:int" use="required" />
								<xs:attribute name="value" type="xs:double" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="globalHolonObservationsType">
		<xs:sequence>
			<xs:element name="globalObservations" type="observationsType"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="holonObservations" type="observationsType"
				minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="observationsType">
		<xs:sequence>
			<xs:element name="observation" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="measure" type="measureType"
							minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="state" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== franc90/DispatchRider/tmp_tests/LRC1_2_4.xls_clustable.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ClusTable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" learning="false" xsi:noNamespaceSchemaLocation="xml/schemes/clustable.xsd">
    <structure>
        <globalMeasures>
            <measure name="M1" value="avg(AverageMinDistBetweenAllCommissions)"/>
            <measure name="M2" value="avg(WaitTime)"/>
            <measure name="M3" value="avg(AverageNumberOfComsWithinTimeWinOfAllCommissions)"/>
        </globalMeasures>
        <globalStates k="0.5">
            <state name="S1">
                <measure name="M3" value="0.13541666666666666"/>
                <measure name="M2" value="388.9753124041814"/>
                <measure name="M1" value="4.460404016446416"/>
            </state>
            <state name="S0">
                <measure name="M3" value="0.12871287128712872"/>
                <measure name="M2" value="1192.77692319766"/>
                <measure name="M1" value="4.671617275217671"/>
            </state>
        </globalStates>
        <globalActions factor="0.9" function="2*_holonsCount/holonsCount+bestDist/dist+_costOfCommission/costOfCommission">
            <action STDepth="0" choosingByCost="false" name="A2" simmulatedTrading="0"/>
            <action STDepth="0" choosingByCost="true" name="A1" simmulatedTrading="0"/>
            <action STDepth="0" choosingByCost="false" name="A4" simmulatedTrading="1"/>
            <action STDepth="0" choosingByCost="true" name="A3" simmulatedTrading="1"/>
            <action STDepth="3" choosingByCost="false" name="A6" simmulatedTrading="0"/>
            <action STDepth="3" choosingByCost="true" name="A5" simmulatedTrading="0"/>
            <action STDepth="3" choosingByCost="false" name="A8" simmulatedTrading="1"/>
            <action STDepth="3" choosingByCost="true" name="A7" simmulatedTrading="1"/>
            <action STDepth="8" choosingByCost="true" name="A11" simmulatedTrading="1"/>
            <action STDepth="8" choosingByCost="true" name="A9" simmulatedTrading="0"/>
            <action STDepth="8" choosingByCost="false" name="A10" simmulatedTrading="0"/>
            <action STDepth="8" choosingByCost="false" name="A12" simmulatedTrading="1"/>
        </globalActions>
        <holonMeasures>
            <measure name="M1" value="AverageMinDistBetweenUndeliveredCommissions"/>
            <measure name="M2" value="WaitTime"/>
            <measure name="M3" value="AverageNumberOfComsWithinTimeWinOfAllCommissions"/>
        </holonMeasures>
        <holonStates k="0.5">
            <state name="S1">
                <measure name="M3" value="0.13541666666666666"/>
                <measure name="M2" value="388.9753124041814"/>
                <measure name="M1" value="4.460404016446416"/>
            </state>
            <state name="S0">
                <measure name="M3" value="0.12871287128712872"/>
                <measure name="M2" value="1192.77692319766"/>
                <measure name="M1" value="4.671617275217671"/>
            </state>
        </holonStates>
        <holonActions factor="0.9" function="2*_holonCommissions/holonCommissions+_costOfCommission/costOfCommission">
            <action algorithm="BruteForceAlgorithm" name="A2" simmulatedTrading="true"/>
            <action algorithm="BruteForceAlgorithm" name="A1" simmulatedTrading="false"/>
            <action algorithm="BruteForceAlgorithm2" name="A4" simmulatedTrading="true"/>
            <action algorithm="BruteForceAlgorithm2" name="A3" simmulatedTrading="false"/>
        </holonActions>
    </structure>
    <content>
        <globalTableContent>
            <state name="S1">
                <action name="A2" useCount="8" value="132.38337315846533"/>
                <action name="A1" useCount="5" value="128.1354183389903"/>
                <action name="A4" useCount="7" value="130.89091575229585"/>
                <action name="A3" useCount="7" value="133.09453276701078"/>
                <action name="A6" useCount="6" value="129.7726254656561"/>
                <action name="A5" useCount="6" value="131.2501870809686"/>
                <action name="A8" useCount="6" value="132.12618082392828"/>
                <action name="A7" useCount="10" value="135.33901380910928"/>
                <action name="A11" useCount="7" value="128.04238506014576"/>
                <action name="A10" useCount="5" value="127.96827016296763"/>
                <action name="A9" useCount="8" value="128.3548193649529"/>
                <action name="A12" useCount="5" value="127.27042995069849"/>
            </state>
            <state name="S0">
                <action name="A2" useCount="1" value="94.35176146038881"/>
                <action name="A1" useCount="1" value="7.388435172070022"/>
                <action name="A4" useCount="1" value="119.42669963337758"/>
                <action name="A3" useCount="1" value="63.34148279800776"/>
                <action name="A6" useCount="0" value="0.0"/>
                <action name="A5" useCount="1" value="103.6045061736688"/>
                <action name="A8" useCount="0" value="0.0"/>
                <action name="A7" useCount="0" value="0.0"/>
                <action name="A11" useCount="0" value="0.0"/>
                <action name="A10" useCount="0" value="0.0"/>
                <action name="A9" useCount="0" value="0.0"/>
                <action name="A12" useCount="1" value="111.9319764156208"/>
            </state>
        </globalTableContent>
        <holonTableContent>
            <state name="S1">
                <action name="A2" useCount="4" value="10.317"/>
                <action name="A1" useCount="37" value="0.0"/>
                <action name="A4" useCount="6" value="12.285300000000001"/>
                <action name="A3" useCount="39" value="0.0"/>
            </state>
            <state name="S0">
                <action name="A2" useCount="2" value="3.0"/>
                <action name="A1" useCount="2" value="0.0"/>
                <action name="A4" useCount="1" value="5.7"/>
                <action name="A3" useCount="2" value="0.0"/>
            </state>
        </holonTableContent>
    </content>
</ClusTable>
