=== franc90/DispatchRider/xml/schemes/mltable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">        

	<xs:element name="MLTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="structure" type="structureType" minOccurs="1" maxOccurs="1"/>
				<xs:element name="content" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="globalTableContent" type="contentType" minOccurs="0" maxOccurs="1"/>
							<xs:element name="holonTableContent" type="contentType" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>	
	</xs:element>
	
	<xs:complexType name="structureType">
		<xs:sequence>
			<xs:element name="globalStates" type="statesType" minOccurs="0" maxOccurs="1" />
			<xs:element name="globalActions" type="actionsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="holonStates" type="statesType" minOccurs="0" maxOccurs="1" />
			<xs:element name="holonActions" type="holonActionsType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="statesType">
		<xs:sequence>
			<xs:element name="state" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="value" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="k" type="xs:double" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="actionsType">
		<xs:sequence>
			<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="sendingType" type="xs:string" default="null"/>
					<xs:attribute name="choosingByCost" type="xs:string" default="null"/>
					<xs:attribute name="simmulatedTrading" type="xs:int" default="-1"/>
					<xs:attribute name="STDepth" type="xs:int" default="-1"/>
					<xs:attribute name="chooseWorstCommission" type="xs:string" default="null"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="function" type="xs:string" use="required"/>
		<xs:attribute name="factor" type="xs:double" use="required"/>
		<xs:attribute name="deterministic" type="xs:boolean" default="true"/>
	</xs:complexType>
	
	
	<xs:complexType name="holonActionsType">
		<xs:sequence>
			<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="algorithm" type="xs:string" default="null"/>
					<xs:attribute name="newCommissionCostByDist" type="xs:string" default="null"/>
					<xs:attribute name="simmulatedTrading" type="xs:string" default="null"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="function" type="xs:string" use="required"/>
		<xs:attribute name="factor" type="xs:double" use="required"/>
		<xs:attribute name="deterministic" type="xs:boolean" default="true"/>
	</xs:complexType>

	<xs:complexType name="contentType">
		<xs:sequence>
			<xs:element name="state" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="useCount" type="xs:int" use="required"/>
								<xs:attribute name="value" type="xs:double" use="required"/>
							</xs:complexType>
						</xs:element> 
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== franc90/DispatchRider/tmp_tests/LRC2_2_4.xls_table.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<MLTable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xml/schemes/mltable.xsd">
    <structure>
        <globalStates k="0.5">
            <state name="S10" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S3" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S11" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S4" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S5" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S6" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S7" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S8" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S12" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S9" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S2" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S1" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
        </globalStates>
        <globalActions factor="0.9" function="2*_holonsCount/holonsCount+_dist/dist+_costOfCommission/costOfCommission">
            <action STDepth="0" choosingByCost="false" name="A2" simmulatedTrading="0"/>
            <action STDepth="0" choosingByCost="true" name="A1" simmulatedTrading="0"/>
            <action STDepth="0" choosingByCost="false" name="A4" simmulatedTrading="1"/>
            <action STDepth="0" choosingByCost="true" name="A3" simmulatedTrading="1"/>
            <action STDepth="3" choosingByCost="false" name="A6" simmulatedTrading="0"/>
            <action STDepth="3" choosingByCost="true" name="A5" simmulatedTrading="0"/>
            <action STDepth="3" choosingByCost="false" name="A8" simmulatedTrading="1"/>
            <action STDepth="3" choosingByCost="true" name="A7" simmulatedTrading="1"/>
            <action STDepth="8" choosingByCost="true" name="A11" simmulatedTrading="1"/>
            <action STDepth="8" choosingByCost="false" name="A10" simmulatedTrading="0"/>
            <action STDepth="8" choosingByCost="true" name="A9" simmulatedTrading="0"/>
            <action STDepth="8" choosingByCost="false" name="A12" simmulatedTrading="1"/>
        </globalActions>
        <holonStates k="0.5">
            <state name="S10" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S3" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S11" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S4" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S5" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S6" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S7" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S8" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S12" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &gt;= 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S9" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &gt;= 4"/>
            <state name="S2" value="avg(AverageMinDistBetweenAllCommissions) &gt;= 2.63 &amp;&amp; avg(AverageMinDistBetweenAllCommissions) &lt; 7.89 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
            <state name="S1" value="avg(AverageMinDistBetweenAllCommissions) &lt; 2.63 &amp;&amp; avg(WaitTime) &lt; 10 &amp;&amp; avg(AverageNumberOfComsWithinTimeWinOfAllCommissions) &lt; 4"/>
        </holonStates>
        <holonActions factor="0.9" function="2*_holonCommissions/holonCommissions+_costOfCommission/costOfCommission">
            <action algorithm="BruteForceAlgorithm" name="A2" simmulatedTrading="true"/>
            <action algorithm="BruteForceAlgorithm" name="A1" simmulatedTrading="false"/>
            <action algorithm="BruteForceAlgorithm2" name="A4" simmulatedTrading="true"/>
            <action algorithm="BruteForceAlgorithm2" name="A3" simmulatedTrading="false"/>
        </holonActions>
    </structure>
    <content>
        <globalTableContent>
            <state name="S3">
                <action name="A2" useCount="1" value="4.0"/>
                <action name="A1" useCount="0" value="0.0"/>
                <action name="A4" useCount="0" value="0.0"/>
                <action name="A3" useCount="0" value="0.0"/>
                <action name="A6" useCount="0" value="0.0"/>
                <action name="A5" useCount="0" value="0.0"/>
                <action name="A8" useCount="0" value="0.0"/>
                <action name="A7" useCount="0" value="0.0"/>
                <action name="A11" useCount="0" value="0.0"/>
                <action name="A9" useCount="0" value="0.0"/>
                <action name="A10" useCount="0" value="0.0"/>
                <action name="A12" useCount="1" value="7.6"/>
            </state>
            <state name="S10">
                <action name="A2" useCount="0" value="0.0"/>
                <action name="A1" useCount="0" value="0.0"/>
                <action name="A4" useCount="0" value="0.0"/>
                <action name="A3" useCount="0" value="0.0"/>
                <action name="A6" useCount="0" value="0.0"/>
                <action name="A5" useCount="0" value="0.0"/>
                <action name="A8" useCount="0" value="0.0"/>
                <action name="A7" useCount="0" value="0.0"/>
                <action name="A11" useCount="0" value="0.0"/>
                <action name="A9" useCount="0" value="0.0"/>
                <action name="A10" useCount="0" value="0.0"/>
                <action name="A12" useCount="0" value="0.0"/>
            </state>
            <state name="S4">
                <action name="A2" useCount="19" value="43.05721274754337"/>
                <action name="A1" useCount="15" value="43.05721274754337"/>
                <action name="A4" useCount="23" value="43.05721274754337"/>
                <action name="A3" useCount="13" value="43.05721274754337"/>
                <action name="A6" useCount="30" value="43.05721274754337"/>
                <action name="A5" useCount="19" value="43.05721274754337"/>
                <action name="A8" useCount="26" value="43.05721274754337"/>
                <action name="A7" useCount="34" value="43.05721274754337"/>
                <action name="A11" useCount="27" value="43.05721274754337"/>
                <action name="A9" useCount="19" value="43.39690305282596"/>
                <action name="A10" useCount="19" value="43.39690305282596"/>
                <action name="A12" useCount="23" value="43.05721274754337"/>
            </state>
            <state name="S11">
                <action name="A2" useCount="1" value="43.05721274754337"/>
