=== franc90/DispatchRider/agenty_testy/xml/schemes/graphChanges.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="graphChanges">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="change" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="change">
        <xs:complexType>
            <xs:sequence>
				<xs:element ref="link" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="time" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="link">
        <xs:complexType>
            <xs:attribute name="sPoint" type="xs:integer" use="required"/>
            <xs:attribute name="ePoint" type="xs:integer" use="required"/>
            <xs:attribute name="cost" type="xs:double" use="required"/>
            <xs:attribute name="both" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== franc90/DispatchRider/importedChanges.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<graphChanges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xml/schemes/graphChanges.xsd">
    <change time="0">
        <link both="false" cost="32.93807641633729" ePoint="8" sPoint="6"/>
        <link both="false" cost="36.48969166210545" ePoint="8" sPoint="2"/>
        <link both="false" cost="55.01306560308073" ePoint="8" sPoint="7"/>
        <link both="false" cost="31.323414252153487" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.824524062906468" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.205109529945656" ePoint="5" sPoint="8"/>
        <link both="false" cost="30.835646006783843" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.512116502619007" ePoint="4" sPoint="7"/>
        <link both="false" cost="33.704078193461406" ePoint="7" sPoint="4"/>
        <link both="false" cost="52.83317923656056" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.506817789540303" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.485012059262662" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.644154634373544" ePoint="6" sPoint="8"/>
        <link both="false" cost="31.867431485022305" ePoint="7" sPoint="1"/>
    </change>
    <change time="300">
        <link both="false" cost="60.679611650485434" ePoint="8" sPoint="6"/>
        <link both="false" cost="47.27014890096904" ePoint="8" sPoint="2"/>
        <link both="false" cost="79.69715082685794" ePoint="8" sPoint="7"/>
        <link both="false" cost="52.88207297726071" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.7096018735363" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.05766572676508" ePoint="5" sPoint="8"/>
        <link both="false" cost="43.67765887748417" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.57876454582296" ePoint="4" sPoint="7"/>
        <link both="false" cost="40.51863857374392" ePoint="7" sPoint="4"/>
        <link both="false" cost="51.07904482186183" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.657049600746051" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.336583153837433" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.518746760352474" ePoint="6" sPoint="8"/>
        <link both="false" cost="37.61519653940192" ePoint="7" sPoint="1"/>
    </change>
    <change time="600">
        <link both="false" cost="41.85851820845542" ePoint="8" sPoint="6"/>
        <link both="false" cost="47.75549188156638" ePoint="8" sPoint="2"/>
        <link both="false" cost="61.003507701692854" ePoint="8" sPoint="7"/>
        <link both="false" cost="34.35245620061834" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.627230974943318" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.514104778353483" ePoint="5" sPoint="8"/>
        <link both="false" cost="36.01656762110571" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.48171536827602" ePoint="4" sPoint="7"/>
        <link both="false" cost="50.83884087442806" ePoint="7" sPoint="4"/>
        <link both="false" cost="55.50159567087554" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.420740063956144" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.263163822717802" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.355893708834884" ePoint="6" sPoint="8"/>
        <link both="false" cost="45.41326067211626" ePoint="7" sPoint="1"/>
    </change>
    <change time="900">
        <link both="false" cost="51.255766273705795" ePoint="8" sPoint="6"/>
        <link both="false" cost="48.828125" ePoint="8" sPoint="2"/>
        <link both="false" cost="50.24494410249969" ePoint="8" sPoint="7"/>
        <link both="false" cost="38.69220352099052" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.50483202945237" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.52073732718894" ePoint="5" sPoint="8"/>
        <link both="false" cost="39.888312724371765" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.287318697443423" ePoint="4" sPoint="7"/>
        <link both="false" cost="49.689440993788814" ePoint="7" sPoint="4"/>
        <link both="false" cost="50.53695514845231" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.537352177675224" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.643476742155208" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.664528169835531" ePoint="6" sPoint="8"/>
        <link both="false" cost="47.64173415912339" ePoint="7" sPoint="1"/>
    </change>
    <change time="1200">
        <link both="false" cost="76.89350249903883" ePoint="8" sPoint="6"/>
        <link both="false" cost="57.95421616922631" ePoint="8" sPoint="2"/>
        <link both="false" cost="89.72633467922836" ePoint="8" sPoint="7"/>
        <link both="false" cost="74.73841554559043" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.53203021391916" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.849745230477545" ePoint="5" sPoint="8"/>
        <link both="false" cost="41.1522633744856" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.445576284765938" ePoint="4" sPoint="7"/>
        <link both="false" cost="67.27211570803901" ePoint="7" sPoint="4"/>
        <link both="false" cost="54.839594187003016" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.590171534538712" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.594202898550725" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.77648236471766" ePoint="6" sPoint="8"/>
        <link both="false" cost="67.65899864682004" ePoint="7" sPoint="1"/>
    </change>
    <change time="1500">
        <link both="false" cost="73.07270734380708" ePoint="8" sPoint="6"/>
        <link both="false" cost="57.0287995437696" ePoint="8" sPoint="2"/>
        <link both="false" cost="69.3721817551162" ePoint="8" sPoint="7"/>
        <link both="false" cost="51.8000518000518" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.196954428395477" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.025966150283919" ePoint="5" sPoint="8"/>
        <link both="false" cost="107.64262648008612" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.463945890175399" ePoint="4" sPoint="7"/>
        <link both="false" cost="79.96801279488206" ePoint="7" sPoint="4"/>
        <link both="false" cost="75.20210565895844" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.464603038119806" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.523392486748099" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.379800853485063" ePoint="6" sPoint="8"/>
        <link both="false" cost="62.69592476489028" ePoint="7" sPoint="1"/>
    </change>
    <change time="1800">
        <link both="false" cost="50.92946269416858" ePoint="8" sPoint="6"/>
        <link both="false" cost="54.55537370430988" ePoint="8" sPoint="2"/>
        <link both="false" cost="57.778419760219556" ePoint="8" sPoint="7"/>
        <link both="false" cost="38.08073115003808" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.292417141889223" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.582117211026176" ePoint="5" sPoint="8"/>
        <link both="false" cost="86.35578583765113" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.259359342453415" ePoint="4" sPoint="7"/>
        <link both="false" cost="57.48778384593274" ePoint="7" sPoint="4"/>
        <link both="false" cost="87.73853915332309" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.338511253472419" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.198835321126603" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.375917183322905" ePoint="6" sPoint="8"/>
        <link both="false" cost="64.24670735624798" ePoint="7" sPoint="1"/>
    </change>
    <change time="2100">
        <link both="false" cost="42.535091450446615" ePoint="8" sPoint="6"/>
        <link both="false" cost="49.82561036372696" ePoint="8" sPoint="2"/>
        <link both="false" cost="62.764788953397144" ePoint="8" sPoint="7"/>
        <link both="false" cost="48.75670404680643" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.758480804280087" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.310298026352994" ePoint="5" sPoint="8"/>
        <link both="false" cost="58.5308750365818" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.48171536827602" ePoint="4" sPoint="7"/>
        <link both="false" cost="52.45213742460005" ePoint="7" sPoint="4"/>
        <link both="false" cost="63.1811720107408" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.47710317915758" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.205737337516808" ePoint="2" sPoint="8"/>
        <link both="false" cost="11.45737855178735" ePoint="6" sPoint="8"/>
        <link both="false" cost="48.86391399951136" ePoint="7" sPoint="1"/>
    </change>
    <change time="2400">
        <link both="false" cost="49.65243296921549" ePoint="8" sPoint="6"/>
        <link both="false" cost="58.428279287174995" ePoint="8" sPoint="2"/>
        <link both="false" cost="58.33454863642993" ePoint="8" sPoint="7"/>
        <link both="false" cost="53.34755934915977" ePoint="8" sPoint="5"/>
        <link both="false" cost="11.513441943469" ePoint="3" sPoint="7"/>
        <link both="false" cost="11.55001155001155" ePoint="5" sPoint="8"/>
        <link both="false" cost="41.3992962119644" ePoint="7" sPoint="3"/>
        <link both="false" cost="11.265067027148811" ePoint="4" sPoint="7"/>
        <link both="false" cost="55.6947925368978" ePoint="7" sPoint="4"/>
        <link both="false" cost="62.893081761006286" ePoint="7" sPoint="8"/>
        <link both="false" cost="11.372036163074998" ePoint="1" sPoint="7"/>
        <link both="false" cost="11.19632760454571" ePoint="2" sPoint="8"/>
